### ISSUE TITLE
Reveal Spoiler Images preference configuration not working

### ISSUE THREAD

**Issue by cdobrich** [Pashe/8chanX#25]
Reveal Spoiler configuration setting is not being honored. In the 8chan-X options, if you check Reveal Spoiler Images, and reload the page, the option is unchecked again. If you manually enter the setting "revealImageSpoilers":"true" into the imported settings, the script does not honor those settings either.

The only thing the script honors if you edit the code itself, changing the default value. It also goes in reverse, if you make the setting by default reveal images, they can never be disabled no matter what you try through the configuration window.

Tested with Firefox 37.0.2 64-bit on Linux on test urls: 
http://8ch.net/co/res/165049.html
http://8ch.net/co/res/164389.html

**Comment by Pashe** [comment]
Make sure you're using [Pure](https://github.com/Pashe/8chanX/tree/2-0_pure). The plain 2-0 branch doesn't work with FF 28+

**Comment by cdobrich** [comment]
Okay that seems to have fixed it. I was not aware of that problem.
