### ISSUE TITLE
8chan X Image Hover Doesn't Work

### ISSUE THREAD

**Issue by KrowofAgony** [Pashe/8chanX#33]
![8chanx image hover doesn t work](https://cloud.githubusercontent.com/assets/7153059/18149863/d6c4765e-6fb0-11e6-8686-7b7f2e5c665e.png)

The Image Hover doesn't work in 8chan X.

It has been going on for several months now.

The version I am using is 8chan X Pure.

**Comment by Pashe** [comment]
Image hover was moved into 8chan's default JS in [early 2015](https://github.com/Pashe/8chanX/commit/77692a29aff351ac9660b23f8e44f3350b132eed). There's a [thread about this on /operate/](https://8ch.net/operate/res/60063.html), but nobody seems to give a shit.
