### ISSUE TITLE
Option to hide post form

### ISSUE THREAD

**Issue by ButchDeLoria** [Pashe/8chanX#6]
Would it be possible to add an option to completely hide the post form at the top of every page, and let the user use only the quick reply post form?

**Comment by Pashe** [comment]
Maybe in [Orn8](https://gist.github.com/Pashe/c453b8537e2fa84e854d), but I don't really think it belongs in 8chanX.

If you put this in your user JS, it should do what you want.

``` js
if (active_page=="thread") {
    $('form[action="/post.php"]:not(#quick-reply) > table, .board-settings').hide();
    $('form[action="/post.php"]:not(#quick-reply)').css("margin-bottom", 0);
}
```
