### ISSUE TITLE
image hover re-do

### ISSUE THREAD

**Issue by anonish** [Pashe/8chanX#9]
I totally hated your "image hover fix" and i'm really bad at github so using version 2.0.0.1422241170
ie commit eb5f6878c94964dacde218530628f68d59c3ab38
along with the fix #8 from 
e26772bfa24c27a7cc9c2cffb7217a3b32ffb2fa
(the "#all" pages fix)
i came up with this, which works with all image file types, keeps the "follow mouse around" from version 2.0.0.1422344710 and discards your superbuggy and long "image hover fix" and just adds two lines instead of that whole mess (no offense) ;^)
(diff format)

```

--- 8chan-x.user-old.js 2015-01-29 18:20:42.198115233 -0600
+++ 8chan-x.user.js     2015-01-29 18:45:20.810104904 -0600
@@ -1,4 +1,4 @@
-// ==UserScript==
+// ==UserScript==
 // @name        Pashe's 8chanX v2 [pure]
 // @version     2.0.0.1422344710
 // @description Small userscript to improve 8chan
@@ -306,6 +306,7 @@
        var pic;
        if ($(this)[0].tagName == "IMG") {pic = $(this);}
        else if ($(this)[0].tagName == "CANVAS") {pic = $(this).next();}
+       var picSrc=$(this).parent().attr("href");

        var picUrl = pic.attr("src");
        if (picUrl.indexOf('spoiler.png') >= 0) {picUrl = $(this).parent().attr("href");}
@@ -334,7 +335,7 @@
                var newpic = pic.clone();
                newpic.attr("id",picId);
                newpic.css('display', 'block').css('position', 'absolute').css('z-index', '200').css("margin", "0px").css("padding", "0px");
-               newpic.attr("src",picUrl.replace("/thumb/","/src/"));
+               newpic.attr("src",picSrc);

                if (picRightEdge > windowWidth) {
                        newpic.css('left', (e.pageX + (windowWidth - picRightEdge))).css('top', top);
@@ -1204,8 +1205,8 @@
 ////////////////
 //EVENT HANDLERS
 ////////////////
-if (isOnThread()) {
-       window.$(document).on('new_post', function (e, post) { try {
+if (unsafeWindow.jQuery) {
+       unsafeWindow.$(document).on('new_post', function (e, post) { try {
                onNewPostRelativeTime(post);
                onNewPostImageHover(post);
                onNewPostRISLinks(post);

```

works on threads and index.html#all pages as well.  gifs only hover on page 1 however, and i'm sure it's got something to do with fix #8 (or the canvas element), maybe you can figure that part out.

**Comment by anonish** [comment]
i stand corrected, it does seem to work for gifs past page 1 as well, however it does throw out the error after each new page loads.  Despite the error (ie. clicking ok, closing the error box), image hover does continue to work past page 1 (in #all pages)

```
"8chanX experienced an error. Please include the following information with your report:
[code]TypeError in 8chan-x.user.js/newpost @ L495 C?: postID is null

Version: Pashe's 8chanX v2 [pure] (2-0_pure@2.0.0.1422344710)
Greasemonkey: 2.3
Active page: index
Browser: Firefox/35.0
User agent: Mozilla/5.0 (X11; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0
Location: https://8ch.net/meta/#all
Stack:
  notifyReplies/<@file:8chan-x.user.js:495:1
  .each@https://8ch.net/meta/main.js:455:2878
  n.prototype.each@https://8ch.net/meta/main.js:455:845
  notifyReplies@file:8chan-x.user.js:492:2
  .each@https://8ch.net/meta/main.js:455:2878
  n.prototype.each@https://8ch.net/meta/main.js:455:845
  onNewPostNotifications@file:8chan-x.user.js:1189:3
  @file:8chan-x.user.js:1213:3
  n.event.dispatch@https://8ch.net/meta/main.js:456:6352
  n.event.add/r.handle@https://8ch.net/meta/main.js:456:3162
  n.event.trigger@https://8ch.net/meta/main.js:456:5510
  .trigger/<@https://8ch.net/meta/main.js:456:11472
  .each@https://8ch.net/meta/main.js:455:2878
  n.prototype.each@https://8ch.net/meta/main.js:455:845
  .trigger@https://8ch.net/meta/main.js:456:11451
  load_next_page/</</<@https://8ch.net/meta/main.js:4431:11
  [/code]"
```

**Comment by Pashe** [comment]
I'm not going back to the old hover code. You think [this](https://github.com/Pashe/8chanX/blob/0306b7299f8b5fdd57bd35b4189a601441f0312e/8chan-x.user.js#L311) is messier than [this](https://github.com/Pashe/8chanX/blob/c19aba12ea92fcba11f767d9bde454270bf28f18/8chan-x.user.js#L311)? The only really bad parts of the new thing are these two lines:

``` js
    var fullUrl = $this.parent().attr("href").match("src")?$this.parent().attr("href"):$this.attr("src").replace("thumb", "src");
    var fileExtension = fullUrl.match(/\.([a-z0-9]+)(&loop.*)?$/i)!==null?fullUrl.match(/\.([a-z0-9]+)(&loop.*)?$/i)[1]:"unknown";
```

And they're going to be cleaned up soon anyway.

---

About the error you're getting: you probably forgot to patch notifyReplies.

**Comment by anonish** [comment]
> About the error you're getting: you probably forgot to patch notifyReplies.

Many thanks, that was it.

I'm going to do a clean up of the hover code over the weekend when i'm not half asleep, and find a way to merge yours and the other because I _really_ want that "hovered image follows mouse" thing and i dont like the resize hover thing.
